# Generated by Django 3.2.4 on 2021-06-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_graduated',
            field=models.DateField(),
        ),
    ]
