# Generated by Django 3.2.4 on 2021-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_doctor_date_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_graduated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
