# Generated by Django 3.2.4 on 2021-09-21 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField()),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_by', to=settings.AUTH_USER_MODEL)),
                ('to_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_to', to='account.doctor')),
            ],
        ),
    ]
