# Generated by Django 3.2.4 on 2021-09-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210921_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
