# Generated by Django 3.2.4 on 2021-09-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmodel',
            old_name='reveiver',
            new_name='receiver',
        ),
    ]
