# Generated by Django 3.2.4 on 2021-09-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_reveiver_threadmodel_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='receiver',
            new_name='receiver_user',
        ),
    ]
