# Generated by Django 3.1.7 on 2021-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpoint', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
