# Generated by Django 3.1.7 on 2021-03-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthpoint', '0003_auto_20210306_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titlea',
        ),
    ]
