# Generated by Django 3.1.7 on 2021-03-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthpoint', '0004_auto_20210306_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titlea',
            new_name='title',
        ),
    ]
