# Generated by Django 3.2.4 on 2021-09-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_receiver_messagemodel_receiver_user'),
        ('healthpoint', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.threadmodel'),
        ),
    ]
